### ISSUE TITLE
Буква "й"

### ISSUE THREAD

**Issue by sleirsgoevy** [Tirondzo/CG-2-2019-Task-2#1]
В описании задания буква "й" набрана как два символа (и с краткой). Из-за этого кратка отрисовывается не над "и", как должна, а над следующим символом.

**Comment by Tirondzo** [comment]
Похоже на издержки кодировки. Где наблюдается проблема? На странице гитхаба всё ок.
![image](https://user-images.githubusercontent.com/3998597/68501039-33fb8080-026e-11ea-9692-5917cececa22.png)

**Comment by sleirsgoevy** [comment]
На скриншоте -- единственная буква "й" в абзаце, отрисованная правильно.

**Comment by Tirondzo** [comment]
Проще сказать при каких условиях оно отрисовывается неверно и скинуть скриншот, чем заставлять меня делать скриншоты, что всё ок.

![image](https://user-images.githubusercontent.com/3998597/68508899-b0975a80-0280-11ea-95ea-9d6bb294ab50.png)

**Comment by Tirondzo** [comment]
Исправлено в этом коммите: https://github.com/Tirondzo/CG-2-2019-Task-2/commit/c4e80426a49042cd07683feac727cbe7c0f8f925
