### ISSUE TITLE
[CRITICAL] `make clean` стирает шейдеры

### ISSUE THREAD

**Issue by sleirsgoevy** [Tirondzo/CG-2-2019-Task-2#2]
Выполнение команды `make clean` стирает все шейдеры в директории `shaders`.

**Comment by Tirondzo** [comment]
`make clean` удалит шейдеры, только если делать `cmake .` в корне, а не как указано в инструкции, в отдельной папке.
https://github.com/Tirondzo/CG-2-2019-Task-2#installation

Либо прикладывайте больше информации о своей проблеме.
