### ISSUE TITLE
Не собирается проект.

### ISSUE THREAD

**Issue by Ivan-Medvedev** [Tirondzo/CG-2-2019-Task-2#4]
В чем моя ошибка? Я неправильно установил openGL библиотеку? Я запустил строчку из readme: sudo apt install mesa-utils xorg-dev libglu1-mesa-dev cmake make build-essential.
![Screenshot from 2019-11-12 01-21-14](https://user-images.githubusercontent.com/57366927/68625768-00795a00-04eb-11ea-862d-ed7b842df357.png)

**Comment by Tirondzo** [comment]
По идее в этом коммите было исправлено
https://github.com/Tirondzo/CG-2-2019-Task-2/commit/8713856286dc47527ede0cbc27b35c3e7daeeea7

Заберите последнюю версию шаблона и попробуйте снова

**Comment by Ivan-Medvedev** [comment]
Спасибо, всё работает!

**Comment by Tirondzo** [comment]
Отлично!
